export { analyzeFailure } from './analyze';
export { captureState, saveSnapshot, readSnapshot, parseEnvFileKeys, DEFAULT_SNAPSHOT_PATH, CONFIG_FILES } from './snapshot';
export type { CaptureOptions, SnapshotReadResult } from './snapshot';
export { explainIssues, formatAge } from './reporter/explain';
export type { ReportContext } from './reporter/explain';
export { InferenceEngine, sortFindings } from './engine';
export { KNOWN_BREAKING_CHANGES } from './engine/knownBreakingChanges';
export type { BreakingChangeRule } from './engine/knownBreakingChanges';
export { parseVersion, classifyBump } from './engine/semver';
export { RuntimeDetector } from './engine/detectors/RuntimeDetector';
export { DependencyDetector } from './engine/detectors/DependencyDetector';
export { SemanticDependencyDetector } from './engine/detectors/SemanticDependencyDetector';
export { ConfigDetector } from './engine/detectors/ConfigDetector';
export { EnvDetector } from './engine/detectors/EnvDetector';
export { GitDetector } from './engine/detectors/GitDetector';
export * from './internal/types';
